apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/pipthablack/udagram-frontend:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 700m
          requests:
            cpu: 300m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: frontend
